org: scoobies
service: calorie-lens-backend
frameworkVersion: "4"

provider:
  name: aws
  stage: prod
  region: ap-south-1
  runtime: nodejs24.x

  environment:
    CURRENT_AWS_REGION: ap-south-1
    TABLE_NAME: calorie-lens-data-table
    BUCKET_NAME: calorie-lens-assets-bucket

  iam: ${file(aws/iam.yaml)}

plugins:
  - serverless-offline

functions:
  storageApi:
    handler: src/storage/handler.handler
    events:
      - httpApi:
          path: /storage/{proxy+}
          method: ANY
  processImage:
    handler: src/processImage/handler.handler
    events:
      - s3:
          bucket: calorie-lens-assets-bucket
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: images/

resources: ${file(aws/resources.yaml)}
