Resources:
  CalorieLensDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: calorie-lens-data-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
