Resources:
  # AWS DynamoDB Table
  CalorieLensDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: calorie-lens-data-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # AWS S3 Bucket
  CalorieLensAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: calorie-lens-assets-bucket
      LifecycleConfiguration:
        Rules:
          - Id: calorie-lens-assets-bucket-lifecycle
            Status: Enabled
            Prefix: "images/"
            ExpirationInDays: 100
            Transitions:
              - StorageClass: GLACIER_IR
                TransitionInDays: 10
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 5
